# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Apr 21 11:27:27 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Otomat(object):
    def setupUi(self, Otomat):
        Otomat.setObjectName("Otomat")
        Otomat.resize(750, 489)
        self.centralwidget = QtWidgets.QWidget(Otomat)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("#centralwidget{\n"
        "background: white" "}\n")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 370, 85, 27))
        self.pushButton.setObjectName("hesapla")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 370, 85, 27))
        self.pushButton_2.setObjectName("temizle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 0, 361, 441))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/home/oktay/PycharmProjects/Otomat/images/vending-machine.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 281, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 130, 113, 27))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("g_para")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 57, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 57, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 250, 57, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 57, 17))
        self.label_6.setObjectName("label_6")
        self.l_pepsi = QtWidgets.QLabel(self.centralwidget)
        self.l_pepsi.setGeometry(QtCore.QRect(80, 190, 57, 17))
        self.l_pepsi.setText("")
        self.l_pepsi.setObjectName("l_pepsi")
        self.l_kola = QtWidgets.QLabel(self.centralwidget)
        self.l_kola.setGeometry(QtCore.QRect(80, 220, 57, 17))
        self.l_kola.setText("")
        self.l_kola.setObjectName("l_kola")
        self.l_fruko = QtWidgets.QLabel(self.centralwidget)
        self.l_fruko.setGeometry(QtCore.QRect(80, 250, 57, 17))
        self.l_fruko.setText("")
        self.l_fruko.setObjectName("l_fruko")
        self.l_fanta = QtWidgets.QLabel(self.centralwidget)
        self.l_fanta.setGeometry(QtCore.QRect(80, 280, 57, 17))
        self.l_fanta.setText("")
        self.l_fanta.setObjectName("l_fanta")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 220, 57, 17))
        self.label_11.setObjectName("label_11")
        self.l_cikolata = QtWidgets.QLabel(self.centralwidget)
        self.l_cikolata.setGeometry(QtCore.QRect(240, 280, 57, 17))
        self.l_cikolata.setText("")
        self.l_cikolata.setObjectName("l_cikolata")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(180, 280, 57, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(180, 190, 57, 17))
        self.label_14.setObjectName("label_14")
        self.l_sandvic = QtWidgets.QLabel(self.centralwidget)
        self.l_sandvic.setGeometry(QtCore.QRect(240, 220, 57, 17))
        self.l_sandvic.setText("")
        self.l_sandvic.setObjectName("l_sandvic")
        self.l_kek = QtWidgets.QLabel(self.centralwidget)
        self.l_kek.setGeometry(QtCore.QRect(240, 250, 57, 17))
        self.l_kek.setText("")
        self.l_kek.setObjectName("l_kek")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(180, 250, 57, 17))
        self.label_17.setObjectName("label_17")
        self.l_snickers = QtWidgets.QLabel(self.centralwidget)
        self.l_snickers.setGeometry(QtCore.QRect(240, 190, 57, 17))
        self.l_snickers.setText("")
        self.l_snickers.setObjectName("l_snickers")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 320, 57, 17))
        self.label_7.setObjectName("label_7")
        self.l_sonuc = QtWidgets.QLabel(self.centralwidget)
        self.l_sonuc.setGeometry(QtCore.QRect(100, 320, 57, 17))
        self.l_sonuc.setText("")
        self.l_sonuc.setObjectName("l_sonuc")
        Otomat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Otomat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 25))
        self.menubar.setObjectName("menubar")
        Otomat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Otomat)
        self.statusbar.setObjectName("statusbar")
        Otomat.setStatusBar(self.statusbar)

        self.retranslateUi(Otomat)
        QtCore.QMetaObject.connectSlotsByName(Otomat)

    def retranslateUi(self, Otomat):
        _translate = QtCore.QCoreApplication.translate
        Otomat.setWindowTitle(_translate("Otomat", "Otomat"))
        self.pushButton.setText(_translate("Otomat", "Hesapla"))
        self.pushButton_2.setText(_translate("Otomat", "Temizle"))
        self.label_2.setText(_translate("Otomat", "Harcamak İstediğiniz Para Miktarını Giriniz"))
        self.label_3.setText(_translate("Otomat", "Pepsi"))
        self.label_4.setText(_translate("Otomat", "Kola"))
        self.label_5.setText(_translate("Otomat", "Fruko"))
        self.label_6.setText(_translate("Otomat", "Fanta"))
        self.label_11.setText(_translate("Otomat", "sandviç"))
        self.label_13.setText(_translate("Otomat", "çikolata"))
        self.label_14.setText(_translate("Otomat", "Snickers"))
        self.label_17.setText(_translate("Otomat", "kek"))
        self.label_7.setText(_translate("Otomat", "Sonuç :"))

